version: '3'
services:
  elasticsearch:
    image: elasticsearch:7.4.2
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
    volumes:
      - ./config/analysis:/usr/share/elasticsearch/config/analysis
      - elasticsearch:/usr/share/elasticsearch/data
  db:
    image: "hst-docker.artifactory.umn.edu/oracle:12.2.0.1-slim"
    volumes:
      - db:/ORCL
    ports:
      - "1521:1521"
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    environment:
      - ORACLE_SYSTEM_PASSWORD=Oradoc_db1
      - USER=${USER}
      - es_host=elasticsearch
      - theme=umn
    ports:
      - 3000:3000
    depends_on:
      - elasticsearch
      - db
volumes:
  db:
  elasticsearch:
  bundle_cache:
