services:
  openldap:
    image: osixia/openldap:1.5.0
    command: --copy-service --loglevel debug
    volumes:
      - ./ldap-data:/var/lib/ldap
      - ./ldap-config:/etc/ldap/slapd.d
    ports:
      - "389:389"
  elasticsearch:
    image: elasticsearch:8.10.2
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
      - "xpack.ml.enabled=false"
    volumes:
      - ./config/analysis:/usr/share/elasticsearch/config/analysis
      - elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build: .
    command: bash -c "rm -rf tmp/cache/* && rm -f tmp/pids/server.pid && bin/dev"
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    environment:
      - USER=${USER}
      - ELASTICSEARCH_URL=elasticsearch
    ports:
      - "3000:3000"
    depends_on:
      - openldap
      - openldap
      - elasticsearch
      - postgres
volumes:
  postgres:
  elasticsearch:
  bundle_cache:
