development:
  url: "oracle-enhanced://study_finder_development:oracle@db/orclpdb1.localdomain"

test:
  url: "oracle-enhanced://study_finder_test:oracle@db/orclpdb1.localdomain"

staging:
  url: <%= ENV['DATABASE_URL'] %>

production:
  url: <%= ENV['DATABASE_URL'] %>

