# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df75ff4d057aa86a73744a5f0ecf96d1323f701f5d02efb7c3544777452c776d8037eb5b7aeb5241b5bb2d260246c356eb84f6104a21ffd6e3ae0782affcc2b8

test:
  secret_key_base: 8b123420fe9bec0e6014e63ec4cca045e7fd054766a19b24e5f01649d32cdbf23155abe19cdb9f6c8abe7062c86aa06650caf402442d0f4a8e70c5a26b2f0c46

# Do not keep production secrets in the repository,
# instead read values from the environment.
staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
